### ISSUE TITLE
LocationAnnotationNode not stable at a point.

### ISSUE THREAD

**Issue by yadavanand** [ProjectDent/ARKit-CoreLocation#57] opened 2017-10-06 09:32 UTC
I am trying to create simple application in which i place LocationAnnotationNode at a geo coordinate and want to grow and  shrink its size depending upon the distance from it.
The problem is that as i go closer to the geo coordinate the LocationAnnotationNode repositions/resizes itself. 
Also the LocationAnnotationNode is not placed at the exact location( geo coordinate). 
Link of the video demo and code is below. 
Please help me to figure out what am i doing wrong.
[Demo Video](https://youtu.be/ocQCVbSCxI4)
`
import UIKit
import SceneKit
import MapKit
import ARCL
import CoreLocation

class ViewController: UIViewController {

    let sceneLocationView = SceneLocationView()

    @IBOutlet var distancelabel: UILabel!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

            let pinCoordinate = CLLocationCoordinate2D(latitude: 19.057396, longitude: 73.004699)
            let pinLocation = CLLocation(coordinate: pinCoordinate, altitude: 10 )
            let pinImage = UIImage(named: "pin")!
            let pinLocationNode = LocationAnnotationNode(location: pinLocation, image: pinImage)
            pinLocationNode.accessibilityLabel = "garden corner"//loc["place"]
            pinLocationNode.scaleRelativeToDistance = true
            sceneLocationView.locationDelegate = self
            sceneLocationView.addLocationNodeWithConfirmedLocation(locationNode: pinLocationNode)
            self.view.addSubview(sceneLocationView)
    }
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        sceneLocationView.frame = CGRect(
            x: 0,
            y: 0,
            width: self.view.frame.size.width,
            height: self.view.frame.size.height)
        
    }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
      
      sceneLocationView.run()
    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
    self.view.bringSubview(toFront: distancelabel)
    }
}
`
extension ViewController:SceneLocationViewDelegate{

    func sceneLocationViewDidAddSceneLocationEstimate(sceneLocationView: SceneLocationView, position: SCNVector3, location: CLLocation) {

    }
    
    func sceneLocationViewDidRemoveSceneLocationEstimate(sceneLocationView: SceneLocationView, position: SCNVector3, location: CLLocation) {

    }
    
    func sceneLocationViewDidConfirmLocationOfNode(sceneLocationView: SceneLocationView, node: LocationNode) {
       
    }
    
    func sceneLocationViewDidSetupSceneNode(sceneLocationView: SceneLocationView, sceneNode: SCNNode) {
       
    }
    
    func sceneLocationViewDidUpdateLocationAndScaleOfLocationNode(sceneLocationView: SceneLocationView, locationNode: LocationNode) {
        
        guard let currentLocation = sceneLocationView.currentLocation() else{return}
        guard let nodelocation = locationNode.location else{return}
       
        let trimCurLoc = CLLocation(latitude: self.trimround(currentLocation.coordinate.latitude, toDecimalPlaces: 7), longitude: self.trimround(currentLocation.coordinate.longitude, toDecimalPlaces: 7))
        
        let distance = trimCurLoc.distance(from: nodelocation)

        var scale = locationNode.scale.y
        switch distance {
        case 0.0...20.0:
            scale = scale * 1.0
            distancelabel.text = "\(distance)    \(scale)"
            break
        case 20.01...40.0:
            scale = scale * 0.8
            distancelabel.text = "\(distance)    \(scale)"
            break
        case 40.1...60.0:
            scale = scale * 0.6
            distancelabel.text = "\(distance)    \(scale)"
            break
        case 60.01...100.0:
            scale = scale * 0.4
            distancelabel.text = "\(distance)    \(scale)"
            break
        case 100.01...10000.0:
            scale = scale * 0.3
            distancelabel.text = "\(distance)    \(scale)"
            break
        default:
            break
        }
        
        locationNode.scale =  SCNVector3(x: scale, y: scale, z: scale)
    }
}

**Comment by francisjervis** [comment] 2017-10-10 07:42
Probable duplicate of #27

**Comment by Claus79** [comment] 2017-10-10 17:55
I have the same problem. I placed a LocationNode close to my place, when I go there is roughly where I'm expecting to find it but then it starts moving every 2-3 seconds.

**Comment by danglq** [comment] 2018-05-14 02:06
I meet the same this problem. Do you have any solution to resolve? @yadavanand

**Comment by AakashSareen** [comment] 2018-05-14 02:10
I believe multiple people have reported that ARCL works best with larger distances.

**Comment by intere** [comment] 2019-05-17 18:55
The reason you see this "jumping" is because your location is changing and the objects are moving relative to your location and their "real world" location.  I recommend paying attention to your vertical and horizontal accuracy of your current location as reported by CoreLocation.

Closing this issue - stale and as @francisjervis pointed out, this is likely a dupe of https://github.com/ProjectDent/ARKit-CoreLocation/issues/27

**Closed by intere** 2019-05-17 18:55 UTC
