### ISSUE TITLE
Missing Map

### ISSUE THREAD

**Issue by WillRRRR** [ProjectDent/ARKit-CoreLocation#8] opened 2017-07-30 22:32 UTC
Some features are missing.

![img_1219](https://user-images.githubusercontent.com/30376565/28757648-06d5c940-754d-11e7-8af4-5b1b840d38fc.PNG)

**Comment by nighthawk** [comment] 2017-07-31 12:52
The map is only visible in the demo project if you manually set `ViewController.showMapView` to `true`.

**Comment by ProjectDent** [comment] 2017-07-31 20:30
Duplicate of #9

**Closed by ProjectDent** 2017-07-31 20:30 UTC
