### ISSUE TITLE
The repo is empty

### ISSUE THREAD

**Issue by dillingham** [ProjectDent/ARKit-CoreLocation#2] opened 2017-07-27 05:28 UTC

**Comment by chriszielinski** [comment] 2017-07-27 05:37
Can confirm this is in fact an issue. 
Duplicate of #1

**Comment by LomyCool** [comment] 2017-07-27 06:36
I could hardly wait to read sourceCode

**Comment by ProjectDent** [comment] 2017-07-27 12:27
Repo no longer empty. Issue closed.

**Closed by ProjectDent** 2017-07-27 12:27 UTC
