### ISSUE TITLE
App freezes on dismissing after showing sceneLocationView

### ISSUE THREAD

**Issue by Khadim012** [ProjectDent/ARKit-CoreLocation#179] opened 2019-05-13 07:27 UTC
Hi,
I'm adding AnnotationNode using a custom view with image and label for distance.
LocationAnnotationNode(location: location, view: myCustomview)
After showing the annotation on camera, when I dismiss the view controller Application freezes and stuck.

But it works fine when I add annotation node using this method
LocationAnnotationNode(location: location, image: image)

Please give a solution.
Here is the code,

let myView = UIView(frame: CGRect(x: 0, y: 0,width: 200, height: 250))
self.myView.backgroundColor = UIColor.clear
            let imageName = "arPin"
            let image = UIImage(named: imageName)
            let imageView = UIImageView(image: image!)
            imageView.frame = CGRect(x: 0, y: 0,width: 200, height: 250)
            self.myView.addSubview(imageView)

            let label = UILabel(frame: CGRect(x: 0, y: 100, width: 200, height: 18))
            label.textAlignment = .center
            label.text = "distance"
            self.myView.addSubview(label)
self.annotationNode = LocationAnnotationNode(location: location, view: self.myView)

**Comment by intere** [comment] 2019-05-17 17:57
@Khadim012 - what branch are you using?  This should be fixed in the `develop` branch.

**Comment by intere** [comment] 2019-05-17 18:00
FYI - I'm closing this as a dupe of https://github.com/ProjectDent/ARKit-CoreLocation/issues/178

**Closed by intere** 2019-05-17 18:00 UTC
