### ISSUE TITLE
Switch must be exhaustive

### ISSUE THREAD

**Issue by Rjmaurya13** [ProjectDent/ARKit-CoreLocation#101] opened 2018-05-02 19:50 UTC
ARCL project gives error after installing it.

Switch must be exhaustive
Do you want to add missing cases?

**Comment by glouel** [comment] 2018-05-03 12:06
See this patch for the fix : https://github.com/ProjectDent/ARKit-CoreLocation/pull/95

The problem is also mentionned on issue #100

**Comment by aaronbrethorst** [comment] 2018-05-27 07:18
fixed in #95

**Closed by aaronbrethorst** 2018-05-27 07:18 UTC
