### ISSUE TITLE
Solution for flikering nodes while overlapping each other

### ISSUE THREAD

**Issue by pareekkhushboo77** [ProjectDent/ARKit-CoreLocation#73] opened 2017-12-08 08:38 UTC
what can be a good solution to solve flikering the views, can we implement clustering in that case.?

**Comment by ddbien** [comment] 2017-12-19 03:21
I have same issue, can you help me ?

**Comment by wayn** [comment] 2017-12-21 08:25
Same issue, anyone resolved?

**Comment by Higgins2718** [comment] 2017-12-26 20:46
I have this problem as well

**Comment by huntdo** [comment] 2017-12-27 03:30
This is commonly referred to as "Z-fighting" in 3D rendering, i have the same issue

**Comment by Dzionis** [comment] 2018-01-02 11:31
@ddbien Could you share code with popup above the node?

**Comment by ashishbitcot** [comment] 2018-02-06 05:16
I have this problem too, seems like Z-fighting is what we want to solve. Any lead please

**Comment by ProjectDent** [comment] 2018-02-21 12:12
Duplicate of #64

**Closed by ProjectDent** 2018-02-21 12:12 UTC
